# Generated by Django 5.0.1 on 2025-04-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_profile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
