# Generated by Django 5.0.1 on 2025-04-28 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_cart_myorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorders',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Myorders',
        ),
    ]
