# Generated by Django 5.0.1 on 2025-05-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_cart_myorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
