# Generated by Django 5.0.1 on 2025-05-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_myproduct_is_out_of_stock_myproduct_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproduct',
            name='stock',
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='product_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
