# Generated by Django 5.0.1 on 2025-05-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_remove_myproduct_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
