# Generated by Django 5.0.1 on 2025-05-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0008_myproduct_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproduct',
            name='is_out_of_stock',
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='product_quantity',
            field=models.CharField(max_length=200),
        ),
    ]
